### ISSUE TITLE
Wrong description for get-password action

### ISSUE THREAD

**Issue by mpurg** [canonical/mongodb-operator#316]
Description for get-password action reads:
```
Change the admin user's password, which is used by charm.
It is for internal charm users and SHOULD NOT be used by applications.
```
It should probably be `Get the admin user's password...` or similar.

https://github.com/canonical/mongodb-operator/blob/9070c93c78dafa194114fae3c842158095e34648/actions.yaml#L8

**Comment by MiaAltieri** [comment]
Thank you @mpurg - I have submitted a PR for this
