### ISSUE TITLE
Ambiguous description/username

### ISSUE THREAD

**Issue by YHatahet** [canonical/mongodb-operator#319]
In this [page](https://charmhub.io/mongodb/docs/t-deploy-mongodb), the description may be a little ambiguous because it mentions to use the admin user and "admin" as the username, but in the statement below "operator" is used. Consider mentioning that the operator is the name of the admin user (if that is correct), or to update the statement above.

"""
Retrieving the username: In this case, we are using the admin user to connect to MongoDB. Use admin as the username:

`export DB_USERNAME="operator"`
"""

**Comment by a-velasco** [comment]
Closing as the tutorial now mentions more explicitly that the `operator` user is the admin user, as per @YHatahet's suggestion. 

Note: the content mentioned initially has been moved to [this](https://charmhub.io/mongodb/docs/t-access-mongodb) page. 

Thank you for bringing this up!
