### ISSUE TITLE
Reference to MongoDB K8s  + Reference to TLS charm + Typo

### ISSUE THREAD

**Issue by YHatahet** [canonical/mongodb-operator#320]
In the following [page](https://charmhub.io/mongodb/docs/t-enable-security), there are several references to Charmed MongoDB K8s instead of just charmed mongoDB, and there is a link that refers to the previously used TLS charm instead of the new self-signed-certs charm even though the tutorial is using that.
Also, the TLS header has a typo : "**Transcript** Layer Security (TLS)" should become "Transport Layer Security (TLS)"

**Comment by a-velasco** [comment]
Closing after addressing all points mentioned re: https://charmhub.io/mongodb/docs/t-enable-security
