### ISSUE TITLE
In sharded deployments sometimes shards are re-added to config-server without any user interaction

### ISSUE THREAD

**Issue by dmitry-ratushnyy** [canonical/mongodb-operator#380]
## Steps to reproduce

Note: Exact steps to reproduce are not clear.
1. Deploy sharded cluster
2. Wait

## Expected behavior
Existing shards should not be re-added automatically to config-server.

## Actual behavior

<img width="1026" alt="Screenshot 2024-03-19 at 15 01 44" src="https://github.com/canonical/mongodb-operator/assets/132273757/3d2d8234-2a55-4ef0-b94a-391a73bb81ec">

## Versions

Operating system: 

Juju CLI: 

Juju agent: 

Charm revision: 

LXD: 

## Log output

Juju debug log:

**Comment by MiaAltieri** [comment]
@dmitry-ratushnyy Unfortunately I have not been able to re-create this error. Perhaps we can work together to re-create it?

**Comment by dmitry-ratushnyy** [comment]
> @dmitry-ratushnyy Unfortunately I have not been able to re-create this error. Perhaps we can work together to re-create it?

sure

**Comment by MiaAltieri** [comment]
solved #383
