### ISSUE TITLE
update relation data on db unit joining/leaving set

### ISSUE THREAD

**Issue by MiaAltieri** [canonical/mongodb-operator#59]
Right now when a unit gets removed from/added to the replica set the related application is not made aware of this. This can lead to some negative consequences, i.e. an application not being able to connect to the replica set.

To resolve this:
1. either [the relation handler](https://github.com/canonical/mongodb-operator/blob/0896eb8e7901c0cb85ead45227b5b79b7fc75341/lib/charms/mongodb_libs/v0/mongodb_provider.py#L70) or [oversee_users](https://github.com/canonical/mongodb-operator/blob/0896eb8e7901c0cb85ead45227b5b79b7fc75341/lib/charms/mongodb_libs/v0/mongodb_provider.py#L122) should update the relation data fields `uri` and `hosts`. (similar to how [set_relation](https://github.com/canonical/mongodb-operator/blob/0896eb8e7901c0cb85ead45227b5b79b7fc75341/lib/charms/mongodb_libs/v0/mongodb_provider.py#L220) does perhaps in a function called `update_relation_hosts`)
2. Add necessary unit tests
3. Integration test this. Add a test to [test_charm_relations](https://github.com/canonical/mongodb-operator/blob/main/tests/integration/relation_tests/new_relations/test_charm_relations.py) This test should:
- scale the mongodb application by 2 units
- remove the original two units (the ones that were deployed at [the beginning](https://github.com/canonical/mongodb-operator/blob/0896eb8e7901c0cb85ead45227b5b79b7fc75341/tests/integration/relation_tests/new_relations/test_charm_relations.py#L40-L44) of the test)
- have the application perform CRUD operations, similar to [this test](https://github.com/canonical/mongodb-operator/blob/0896eb8e7901c0cb85ead45227b5b79b7fc75341/tests/integration/relation_tests/new_relations/test_charm_relations.py#L54)

**Comment by averma-canonical** [comment]
Hi @MiaAltieri , can I close this?

**Comment by averma-canonical** [comment]
Closing after ack from Mia.
